import { Garment } from '@/types';

export const SAMPLE_GARMENTS: Garment[] = [
  {
    id: 'vintage-levi-501',
    name: '501® Original Fit Vintage Denim Jeans',
    brand: 'Levi Strauss & Co.',
    category: 'jeans',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ3mA6I5JPINncK0X2iLYv50zvD8oATUlEugzcOGgaWRadHAZXJXsoDmixnTGsiF--4WRgRdCK4rdoG7rCsW7-xgcLl_B6QV2sG09734eF0xEVVLCCr4ZIqIW2Qp5NmlzXasWlmXRo&usqp=CAc',
    price: '$98.00',
    description: 'The iconic straight fit jean crafted from 100% heavyweight cotton denim. Classic mid-rise waist with rigid structure.',
    fitType: 'regular',
    material: '100% Cotton Rigid Denim (Non-Stretch)',
    productUrl: 'https://www.levi.com/US/en_US/clothing/men/jeans/501-original-fit-mens-jeans/p/005010114',
    sizes: [
      { size: 'S', waist: 76, hips: 94, inseam: 80, chest: 0, shoulderWidth: 0 },
      { size: 'M', waist: 82, hips: 100, inseam: 81, chest: 0, shoulderWidth: 0 },
      { size: 'L', waist: 88, hips: 106, inseam: 82, chest: 0, shoulderWidth: 0 },
      { size: 'XL', waist: 96, hips: 114, inseam: 82, chest: 0, shoulderWidth: 0 },
      { size: 'XXL', waist: 104, hips: 122, inseam: 83, chest: 0, shoulderWidth: 0 },
    ],
  },
  {
    id: 'heavyweight-unisex-hoodie',
    name: 'Eco-Fleece Heavyweight Streetwear Hoodie',
    brand: 'Patagonia EcoLab',
    category: 'hoodie',
    imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
    price: '$75.00',
    description: 'Ultra-soft 450 GSM organic cotton blend fleece hoodie with dropped shoulders and a modern boxy silhouette.',
    fitType: 'oversized',
    material: '80% Organic Cotton, 20% Recycled Polyester',
    productUrl: 'https://www.patagonia.com/product/unisex-heavyweight-fleece-hoodie',
    sizes: [
      { size: 'XS', chest: 96, waist: 90, hips: 92, shoulderWidth: 46, inseam: 0, sleeveLength: 62 },
      { size: 'S', chest: 102, waist: 96, hips: 98, shoulderWidth: 48, inseam: 0, sleeveLength: 64 },
      { size: 'M', chest: 108, waist: 102, hips: 104, shoulderWidth: 50, inseam: 0, sleeveLength: 65 },
      { size: 'L', chest: 116, waist: 110, hips: 112, shoulderWidth: 52, inseam: 0, sleeveLength: 66 },
      { size: 'XL', chest: 124, waist: 118, hips: 120, shoulderWidth: 54, inseam: 0, sleeveLength: 67 },
    ],
  },
  {
    id: 'formal-italian-blazer',
    name: 'Milano Italian Wool Structured Blazer',
    brand: 'Armani Atelier',
    category: 'blazer',
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
    price: '$240.00',
    description: 'Precision-tailored Italian wool blazer featuring structured shoulder padding, notched lapels, and double-vent back.',
    fitType: 'slim',
    material: '98% Virgin Wool, 2% Elastane',
    productUrl: 'https://www.armani.com/en-us/milano-structured-wool-blazer',
    sizes: [
      { size: 'S', chest: 94, waist: 82, hips: 96, shoulderWidth: 43, inseam: 0, sleeveLength: 63 },
      { size: 'M', chest: 100, waist: 88, hips: 102, shoulderWidth: 45, inseam: 0, sleeveLength: 64 },
      { size: 'L', chest: 106, waist: 94, hips: 108, shoulderWidth: 47, inseam: 0, sleeveLength: 65 },
      { size: 'XL', chest: 112, waist: 100, hips: 114, shoulderWidth: 49, inseam: 0, sleeveLength: 66 },
    ],
  },
  {
    id: 'organic-essential-tee',
    name: 'Pima Cotton Essential Everyday Tee',
    brand: 'Everlane',
    category: 'tshirt',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    price: '$35.00',
    description: 'Long-staple Peruvian Pima cotton crewneck t-shirt. Breathable, durable, pre-shrunk fabric tailored for everyday comfort.',
    fitType: 'regular',
    material: '100% Peruvian Pima Cotton',
    productUrl: 'https://www.everlane.com/products/mens-pima-crew-tee',
    sizes: [
      { size: 'XS', chest: 88, waist: 78, hips: 88, shoulderWidth: 41, inseam: 0 },
      { size: 'S', chest: 94, waist: 84, hips: 94, shoulderWidth: 43, inseam: 0 },
      { size: 'M', chest: 100, waist: 90, hips: 100, shoulderWidth: 45, inseam: 0 },
      { size: 'L', chest: 106, waist: 96, hips: 106, shoulderWidth: 47, inseam: 0 },
      { size: 'XL', chest: 114, waist: 104, hips: 114, shoulderWidth: 49, inseam: 0 },
    ],
  },
  {
    id: 'linen-summer-dress',
    name: 'Mediterranean Linen Wrap Midi Dress',
    brand: 'Reformation Eco',
    category: 'dress',
    imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80',
    price: '$128.00',
    description: 'Effortless wrap-front midi dress made from 100% sustainable European flax linen with a cinchable waist tie.',
    fitType: 'relaxed',
    material: '100% European Flax Linen',
    productUrl: 'https://www.thereformation.com/products/mediterranean-linen-dress',
    sizes: [
      { size: 'XS', chest: 82, waist: 64, hips: 90, shoulderWidth: 36, inseam: 0 },
      { size: 'S', chest: 87, waist: 69, hips: 95, shoulderWidth: 37.5, inseam: 0 },
      { size: 'M', chest: 92, waist: 74, hips: 100, shoulderWidth: 39, inseam: 0 },
      { size: 'L', chest: 98, waist: 80, hips: 106, shoulderWidth: 41, inseam: 0 },
      { size: 'XL', chest: 106, waist: 88, hips: 114, shoulderWidth: 43, inseam: 0 },
    ],
  },
];
